name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Debug Directory and Fix Working Directory
        run: |
          pwd
          ls -lah
          cd connecting-mysql || cd $GITHUB_WORKSPACE
          ls -lah

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install Kind v0.20.0
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/kind
          kind version

      - name: Build JAR file with Correct Directory
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t viha06/connecting-mysql-spring-app:latest .
          docker push viha06/connecting-mysql-spring-app:latest

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create Kind Cluster
        run: |
          kind create cluster --name kind-lab-cluster --wait 300s

      - name: Wait for Cluster to be Ready
        run: |
          for i in {1..30}; do
            kubectl get nodes && break
            echo "Waiting for cluster..."
            sleep 5
          done

      - name: Debug Cluster Info
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Apply MySQL Deployment Non-Fatal
        run: |
          kubectl apply -f k8s . || echo "⚠️ Some manifests failed to apply, continuing anyway"

      

      - name: Apply Spring App Deployment
        run: |
          kubectl apply -f k8s/spring-app-deployment.yaml

      - name: Restart Spring Deployment
        run: |
          kubectl rollout restart deployment/spring-app

